export default function Home() {
  const [value, setValue] = useState("");
  const [result, setResult] = useState("");

  const YOUR_ACCESS_KEY = "4d805f57-49f5-45a9-bbff-86eb6a563ad4"; //api 키

  const onSubmit = (SubmitEvent) => {
    e.preventDefault();

    //axios를 통해서 보내면 된다.
    axios
      .post(
        "http://aiopen.etri.re.kr:8000/WiseNLU",
        {
          argument: {
            analysis_code: "morp", //"morp" 형태소 분석 코드
            text: value,
          },
        },
        {
          headers: {
            //etri에서 발급받은 API키를 넣으면 된다.
            Authorization: YOUR_ACCESS_KEY,
          },
        }
      )
      .then((res) => {
        //결과 값은 return_object에 저장되어 온다.
        const sentenceArray = res.data.return_object.sentence;
        const resultArr = sentenceArray.map((e) => e.morp);
        setResult(JSON.stringify(resultArr));
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form action="" onSubmit={onSubmit}>
          <textarea
            value={value}
            onChange={(e) => setValue(e.target.value)}
          ></textarea>
          <button type="submit">발송</button>
        </form>

        {/*  응답 결과를 JSON.stringfy로 문자열화하고 이렇게 출력한다.  */}
        <div>{result}</div>
      </main>
    </>
  );
}
