import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <header></header>
        {children}
        <footer>
          <address>CopyRight&copy;hykim6856@gmail.com</address>
        </footer>
      </body>
    </html>
  );
}
